# Generated by Django 6.0.1 on 2026-01-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='swiggyDB',
            fields=[
                ('Address', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=10)),
                ('Coupon', models.CharField(max_length=100)),
                ('Upi_id', models.CharField(max_length=100)),
                ('Credit_card_no', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
